ssh compute-044 sudo mount head:/home /home &
ssh compute-045 sudo mount head:/home /home &
ssh compute-046 sudo mount head:/home /home &
ssh compute-047 sudo mount head:/home /home &
ssh compute-048 sudo mount head:/home /home &
ssh compute-049 sudo mount head:/home /home &
ssh compute-050 sudo mount head:/home /home &
ssh compute-051 sudo mount head:/home /home &
ssh compute-052 sudo mount head:/home /home &
ssh compute-054 sudo mount head:/home /home &
ssh compute-055 sudo mount head:/home /home &
ssh compute-056 sudo mount head:/home /home &
ssh compute-058 sudo mount head:/home /home &
ssh compute-059 sudo mount head:/home /home &
ssh compute-060 sudo mount head:/home /home &
ssh compute-061 sudo mount head:/home /home &
ssh compute-062 sudo mount head:/home /home &
ssh compute-063 sudo mount head:/home /home &
ssh compute-064 sudo mount head:/home /home &
ssh compute-065 sudo mount head:/home /home &
ssh compute-066 sudo mount head:/home /home &
ssh compute-067 sudo mount head:/home /home &
ssh compute-068 sudo mount head:/home /home &
ssh compute-069 sudo mount head:/home /home &
ssh compute-070 sudo mount head:/home /home &
ssh compute-071 sudo mount head:/home /home &
ssh compute-072 sudo mount head:/home /home &
ssh compute-073 sudo mount head:/home /home &
ssh compute-074 sudo mount head:/home /home &
ssh compute-075 sudo mount head:/home /home &
ssh compute-076 sudo mount head:/home /home &
ssh compute-077 sudo mount head:/home /home &
ssh compute-078 sudo mount head:/home /home &
ssh compute-079 sudo mount head:/home /home &
ssh compute-080 sudo mount head:/home /home &
ssh compute-083 sudo mount head:/home /home &
ssh compute-084 sudo mount head:/home /home &
ssh compute-085 sudo mount head:/home /home &
ssh compute-086 sudo mount head:/home /home &
ssh compute-087 sudo mount head:/home /home &
ssh compute-088 sudo mount head:/home /home &
ssh compute-089 sudo mount head:/home /home &
ssh compute-090 sudo mount head:/home /home &
ssh compute-092 sudo mount head:/home /home &
ssh compute-093 sudo mount head:/home /home &
ssh compute-094 sudo mount head:/home /home &
ssh compute-095 sudo mount head:/home /home &
ssh compute-096 sudo mount head:/home /home &
ssh compute-097 sudo mount head:/home /home &
ssh compute-098 sudo mount head:/home /home &
ssh compute-099 sudo mount head:/home /home &
ssh compute-100 sudo mount head:/home /home &
ssh compute-101 sudo mount head:/home /home &
ssh compute-102 sudo mount head:/home /home &
ssh compute-103 sudo mount head:/home /home &
ssh compute-104 sudo mount head:/home /home &
ssh compute-105 sudo mount head:/home /home &
ssh compute-106 sudo mount head:/home /home &
ssh compute-107 sudo mount head:/home /home &
ssh compute-108 sudo mount head:/home /home &
ssh compute-109 sudo mount head:/home /home &
ssh compute-110 sudo mount head:/home /home &
ssh compute-111 sudo mount head:/home /home &
ssh compute-113 sudo mount head:/home /home &
ssh compute-114 sudo mount head:/home /home &
